name: Cypress Cloud

on: 
  workflow_dispatch: 
    inputs: 
      spec: 
        description: Run by cypress command lione
        default: cypress/e2e/*
        
jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
      
      - name: Cypress run
        uses: cypress-io/github-action@v5.1.0
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 8b0ae5e3-ef56-4c23-bb46-d665561dec8c
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cypress-e2e-chrome:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
      
      - name: Cypress run
        uses: cypress-io/github-action@v5.1.0
        with:
          install-command: yarn install
          browser: chrome
          record: true
          group: UI chrome
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 8b0ae5e3-ef56-4c23-bb46-d665561dec8c
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cypress-e2e-firefox:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
      
      - name: Cypress run
        uses: cypress-io/github-action@v5.1.0
        with:
          install-command: yarn install
          browser: firefox
          record: true
          group: UI firefox
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 8b0ae5e3-ef56-4c23-bb46-d665561dec8c
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
